apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocikubernetesapp
  labels:
    app: ocikubernetesapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ocikubernetesapp
  template:
    metadata:
      labels:
        app: ocikubernetesapp
    spec:
      containers:
      - name: ocikubernetesapp
        image: patrickguha/ocikubernetesapp:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ocikubernetesapp
  labels:
    app: ocikubernetesapp
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: ocikubernetesapp
